name: "Wait for a workflow"
description: "It waits for a workflow in a different repository to be executed and return the value"
author: "Javier Martinez Alcantara, JM"
inputs:
  githubToken:
    description: "User token to be get enough privileges to trigger the workflow in the other repository"
    required: true
  workspace:
    description: "Github workspace where the repository of the workflow to be invoked is"
    required: true
  repository:
    description: "Repository that contains the workflow to be invoked"
    required: true
  workflow:
    description: "Name of the yaml file or workflow name that represents the workflow"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
