name: Integration Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: jmaralc/wait-for-workflow@master
        with:
          githubToken:  ${{ secrets.GITHUB_TOKEN }}
          workspace: jmaralc
          repository: wait-for-workflow
          workflow: python