name: Lint
on: [workflow_dispatch]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@v1

      - name: Sleep for 3 minutes
        run: sleep 180s
        shell: bash

      - name: Lint
        run: |
          pip install flake8
          flake8 main.py
